version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql