server:
  port: 8079

spring:
  application:
    name: data-generator

data.generator:
  cakes:
    names:
      - 'Медовик'
      - 'Наполеон'
      - 'Чизкейк'
      - 'Прага'
      - 'Морковный'
      - 'Красный бархат'
      - 'Сникерс'
      - 'Графские развалины'
  people:
    first-names:
      male:
        - Александр
        - Алексей
        - Альберт
        - Анатолий
        - Андрей
        - Антон
        - Аркадий
        - Арсений
        - Артём
        - Артемий
        - Артур
        - Борис
        - Вадим
        - Валентин
        - Валерий
        - Василий
        - Виктор
        - Виталий
        - Владимир
        - Владислав
        - Вячеслав
        - Геннадий
        - Георгий
        - Глеб
        - Григорий
        - Даниил
        - Денис
        - Дмитрий
        - Евгений
        - Егор
        - Иван
        - Игорь
        - Илья
        - Кирилл
        - Константин
        - Леонид
        - Макар
        - Максим
        - Михаил
        - Никита
        - Николай
        - Олег
        - Павел
        - Пётр
        - Роман
        - Руслан
        - Семён
        - Сергей
        - Станислав
        - Степан
        - Тарас
        - Тимофей
        - Тимур
        - Фёдор
      female:
        - Алевтина
        - Александра
        - Алина
        - Алла
        - Анастасия
        - Ангелина
        - Анна
        - Валентина
        - Валерия
        - Варвара
        - Василиса
        - Вера
        - Вероника
        - Виктория
        - Галина
        - Дарья
        - Евгения
        - Екатерина
        - Елена
        - Елизавета
        - Зоя
        - Кира
        - Ксения
        - Маргарита
        - Марина
        - Мария
        - Надежда
        - Наталья
        - Нина
        - Оксана
        - Ольга
        - Полина
        - Светлана
        - Татьяна
    last-names:
      - Смирнов
      - Иванов
      - Кузнецов
      - Соколов
      - Попов
      - Петров
      - Лебедев
      - Козлов
      - Новиков
      - Морозов
      - Волков
      - Соловьёв
      - Васильев
      - Зайцев
      - Павлов
      - Семёнов
      - Виноградов
      - Богданов
      - Воробьёв
      - Фёдоров
      - Михайлов
      - Беляев
      - Сидоров
      - Белов
      - Комаров
      - Орлов
      - Киселёв
      - Макаров
      - Андреев
      - Ковалёв
      - Ильин
      - Гусев
      - Титов
      - Кузьмин
      - Кудрявцев
      - Баранов
      - Куликов
      - Алексеев
      - Степанов
      - Яковлев
      - Сорокин
      - Сергеев
      - Романов
      - Захаров
      - Борисов
      - Королёв
      - Денисов
      - Пономарёв
      - Григорьев
      - Лазарев
      - Медведев
      - Ершов
      - Никитин
      - Соболев
      - Рябов
      - Поляков
      - Цветков
      - Данилов
      - Жуков
      - Фролов
      - Журавлёв
      - Николаев
      - Крылов
      - Максимов
      - Белоусов
      - Федотов
      - Дорофеев
      - Егоров
      - Матвеев
      - Бобров
      - Дмитриев
      - Калинин
      - Анисимов
      - Петухов
      - Антонов
      - Тимофеев
      - Никифоров
      - Веселов
      - Филиппов
      - Тарасов
      - Марков
      - Большаков
      - Суханов
      - Миронов
      - Ширяев
      - Александров
      - Коновалов
      - Шестаков
      - Казаков
      - Ефимов
      - Громов
      - Герасимов
      - Фомин
      - Давыдов
      - Мельников
      - Щербаков
      - Блинов
      - Колесников
      - Карпов
      - Афанасьев
      - Власов
      - Маслов
      - Исаков
      - Тихонов
      - Аксёнов
      - Гаврилов
      - Родионов
      - Котов
      - Горбунов
      - Кудряшов
      - Быков
      - Зуев
      - Третьяков
      - Савельев
      - Панов
      - Рыбаков
      - Суворов
      - Абрамов
      - Воронов
      - Мухин
      - Архипов
      - Трофимов
      - Мартынов
      - Емельянов
      - Горшков
      - Чернов
      - Овчинников
      - Голубев
      - Селезнёв
      - Панфилов
      - Копылов
      - Михеев
      - Галкин
      - Назаров
      - Лобанов
      - Лукин
      - Беляков
      - Потапов
      - Некрасов
      - Хохлов
      - Жданов
      - Наумов
      - Шилов
      - Воронцов
      - Ермаков
      - Дроздов
      - Игнатьев
      - Савин
      - Логинов
      - Сафонов
      - Капустин
      - Кириллов
      - Моисеев
      - Елисеев
      - Кошелев
      - Костин
      - Горбачёв
      - Орехов
      - Ефремов
      - Исаев
      - Евдокимов
      - Калашников
      - Кабанов
      - Носков
      - Юдин
      - Кулагин
      - Лапин
      - Прохоров
      - Нестеров
      - Харитонов
      - Агафонов
      - Муравьёв
      - Ларионов
      - Федосеев
      - Зимин
      - Пахомов
      - Шубин
      - Игнатов
      - Филатов
      - Крюков
      - Рогов
      - Кулаков
      - Терентьев
      - Молчанов
      - Владимиров
      - Артемьев
      - Гурьев
      - Зиновьев
      - Гришин
      - Кононов
      - Дементьев
      - Ситников
      - Симонов
      - Мишин
      - Фадеев
      - Комиссаров
      - Мамонтов
      - Носов
      - Гуляев
      - Шаров
      - Устинов
      - Вишняков
      - Евсеев
      - Лаврентьев
      - Брагин
      - Константинов
      - Корнилов
      - Авдеев
      - Зыков
      - Бирюков
      - Шарапов
      - Никонов
      - Щукин
      - Осипов
      - Дьячков
      - Одинцов
      - Сазонов
      - Якушев
      - Красильников
      - Гордеев
      - Самойлов
      - Князев
      - Беспалов
      - Уваров
      - Шашков
      - Бобылёв
      - Доронин
      - Белозёров
      - Рожков
      - Самсонов
      - Мясников
      - Лихачёв
      - Буров
      - Сысоев
      - Фомичёв
      - Русаков
      - Стрелков
      - Гущин
      - Тетерин
      - Колобов
      - Субботин
      - Фокин
      - Блохин
      - Селиверстов
      - Пестов
      - Кондратьев
      - Силин
      - Меркушев
      - Лыткин
      - Туровм
    date-birth-range:
      min: 1960-01-01
      max: 2000-01-01
    mail-providers:
      - gmail.com
      - yandex.ru