name: Build artifact with maven

on:
  workflow_call:
    inputs:
      jdk:
        description: 'JDK to use'
        default: '17'
        required: false
        type: string
      jdk-distribution:
        description: 'JDK distribution to use'
        default: 'temurin'
        required: false
        type: string
      root-folder:
        description: 'Folder containing pom.xml to build'
        default: './'
        required: false
        type: string
      display-name:
        description: 'Artifact name to be built'
        required: true
        type: string
      publish:
        description: 'Is artifact should be published?'
        default: false
        required: false
        type: boolean
      use-codecov:
        description: 'Usd code coverage tool?'
        default: true
        required: false
        type: boolean

jobs:
  build-with-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Set up JDK ${{ inputs.jdk }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.jdk }}
          distribution: ${{ inputs.jdk-distribution }}
          cache: maven

      - name: Build ${{ inputs.display-name }}
        run: cd ${{ inputs.root-folder }} && mvn --batch-mode clean package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Code Coverage
        if: ${{ inputs.use-codecov }}
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Publish ${{ inputs.display-name }}
        if: ${{ inputs.publish }}
        run: cd ${{ inputs.root-folder }} && mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
