name: Build Cakes Manager Services

on:
  pull_request:
    branches: [ master ]

jobs:

  build-common-lib:
    uses: AlexKoltsov/cakes-manager-services/.github/workflows/build-with-maven.yml@docker-push
    with:
      display-name: Common Library
      root-folder: common-lib
      publish: true

  build-cakes-service:
    needs: build-common-lib
    uses: AlexKoltsov/cakes-manager-services/.github/workflows/build-with-maven.yml@docker-push
    with:
      display-name: Cakes Service
      root-folder: cakes-service

  build-orders-service:
    needs: build-common-lib
    uses: AlexKoltsov/cakes-manager-services/.github/workflows/build-with-maven.yml@docker-push
    with:
      display-name: Orders Service
      root-folder: orders-service

  build-people-service:
    needs: build-common-lib
    uses: AlexKoltsov/cakes-manager-services/.github/workflows/build-with-maven.yml@docker-push
    with:
      display-name: People Service
      root-folder: people-service

  build-service-discovery:
    uses: AlexKoltsov/cakes-manager-services/.github/workflows/build-with-maven.yml@docker-push
    with:
      display-name: Service Discovery
      root-folder: service-discovery

  build-data-generator:
    needs: build-common-lib
    uses: AlexKoltsov/cakes-manager-services/.github/workflows/build-with-maven.yml@docker-push
    with:
      display-name: Data Generator
      root-folder: data-generator
