name: Build common lib

on:
  pull_request:
    paths:
      - 'common-lib/**'
    branches: [ master ]

jobs:
  build-common-lib:
    uses: AlexKoltsov/cakes-manager-services/.github/workflows/build-with-maven.yml@docker-push
    with:
      artifact-name: common-lib
