name: Build cakes service

on:
  pull_request:
    paths:
      - 'cakes-service/**'
    branches: [ master ]
  workflow_run:
    workflows: [ "Build common lib" ]
    types:
      - completed

jobs:
  build-cakes-service:
    uses: AlexKoltsov/cakes-manager-services/.github/workflows/build-with-maven.yml@docker-push
    with:
      artifact-name: cakes-service
